<?php
include './config.php';
?>
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content=""/>
    <title>Terms & Conditions</title>
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="css/animate.css">
    <link rel="stylesheet" href="css/icomoon.css">
    <link rel="stylesheet" href="css/main.css">
    <link rel="stylesheet" href="css/color-1.css">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="css/responsive.css">
    <link rel="stylesheet" href="css/transition.css">
    <link href='https://fonts.googleapis.com/css?family=Merriweather:300,300italic,400italic,400,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lato:400,300,300italic,400italic,700,700italic,900italic,900,100italic,100' rel='stylesheet' type='text/css'>
    <script src="js/vendor/modernizr.js"></script>
    <style>
        p{
            font-size: 16px;
        }
    </style>
</head>
<body>
<div id="status">
    <div id="preloader">
        <div class="preloader position-center-center">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
</div>
<div class="wrapper push-wrapper">
    <?php
        include './include/header.php';
    ?>
    <div class="breadcrumb-holder white-bg">
        <div class="container">
            <div class="breadcrumbs">
                <ul>
                    <li><a href="#">Home</a></li>
                    <li>Terms & Conditions</li>
                </ul>
            </div>
        </div>
    </div>
    <main class="main-content">
        <section class="service-nd-mission tc-padding-top white-bg">
            <div class="container">
                <div class="main-heading-holder">
                    <div class="main-heading style-1">
                        <h2><span class="theme-color">Terms & Conditions</span></h2>
                    </div>
                </div>
                <div class="our-service tc-padding-bottom">
                    <div class="row">
                        <p>The document is the e-record in terms of Information Technology Act, 2000 and rules are applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any manual or digital signatures.</p>
                        <h4>Right to Modifications of Terms & Conditions</h4>
                        <p>
                  We may update this Agreement from time to time without notice. Any changes in our terms of use will be incorporated into a revised Agreement that we will post on the Sites. All visitors have the obligation to review changes to this Agreement, including any changes to our Privacy Policy. Unless otherwise specified, such changes shall be effective when they are posted. Your access or use of our Sites constitutes your agreement to be bound by this Agreement, including any changes that exist when you re-access our Sites. IF YOU DO NOT AGREE WITH THE TERMS OF THIS AGREEMENT, OR ANY POSTED GUIDELINES OR RULES, THEN DO NOT USE OUR SITE.
                        </p>
                        <h4>Eligible For Membership rights</h4>
                        <p>
                        Use of the Website is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Website. If you are a minor i.e. under the age of 18 years, you shall not register as a User of the "Skyevo.in.” website and shall not transact on or use the website. As a minor if you wish to use or transact on website, such use or transaction may be made by your legal guardian or parents on the Website.
                        </p>
                        <p>You must be thirteen (13) years of age or older to participate in any activities or services offered on our Sites and/or be a member and receive membership benefits, and you must be eighteen (18) years of age or older to participate in our A-List Invitations. You may not have to be a member to participate in certain contests, sweepstakes and/or special events; however, you must meet the designated minimum age requirements (for example, twenty-one (21) years of age or older) for the specific event.
                        </p>
                        <p>
                           We will establish specific rules and terms for participation in each contest, sweepstakes and/or special event and will post this information on our Sites. We will not knowingly collect personal information from visitors under thirteen (13) years of age for these activities. Upon discovery of the participation of a person under thirteen (13) years of age in such activities, his/her registration or participation will be canceled immediately and all personal information will be deleted from our files.
                        </p>
                        <h4>Registration Obligations</h4>
                        <p>
                          Registration with the Sites is required in order to access certain services, including, without limitation, saving of favorite user ratings, listing reviews and blog and article comment posting. Your registration information will be handled by us in accordance with our Privacy Policy, which you should review prior to registering with us.
                         The information provided on the Site is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country. 

                        </p>
                        <p>
                           Accordingly, those persons who choose to access the Site from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable. 
                        </p>
                           <h4>Purchases and Payment Terms</h4>
                        <p>
                            You agree to provide current, complete, and accurate purchase and account information for all purchases made via the Site “Skyevo.in”. You further agree to promptly update account and payment information, including email address, payment method, and payment card expiration date, so that we can complete your transactions and contact you as needed. Sales tax will be added to the price of purchases as deemed required by us. 
                            You agree to pay all charges at the prices then in effect for your purchases and any applicable shipping fees, and you authorize us to charge your chosen payment provider for any such amounts upon placing your order. 
                            [If your order is subject to recurring charges, then you consent to our charging your payment method on a recurring basis without requiring your prior approval for each recurring charge, until such time as you cancel the applicable order.] We reserve the right to correct any errors or mistakes in pricing, even if we have already requested or received payment.

                        </p>
                        <p>
                           We reserve the right to refuse any order placed through the Site. We may, in our sole discretion, limit or cancel quantities purchased per person, per household, or per order. These restrictions may include orders placed by or under the same customer account, the same payment method, and/or orders that use the same billing or shipping address. We reserve the right to limit or prohibit orders that, in our sole judgment, appear to be placed by dealers, resellers, or distributors. 
                        </p>
                        <h4>User Generated Contributions</h4>
                        <p>
                            The Site may invite you to chat, contribute to, or participate in blogs, message boards, online forums, and other functionality, and may provide you with the opportunity to create, submit, post, display, transmit, perform, publish, distribute, or broadcast content and materials to us or on the Site, including but not limited to text, writings, video, audio, photographs, graphics, comments, suggestions, or personal information or other material (collectively, "Contributions"). 
                        </p>
                        <p>Contributions may be viewable by other users of the Site and through third-party websites. As such, any Contributions you transmit may be treated as non-confidential and non-proprietary. When you create or make available any Contributions, you thereby represent and warrant that:</p>
                        <ul class="list_1"style="font-size:16px;">
                        <li>The creation, distribution, transmission, public display, or performance, and the accessing, downloading, or copying of your Contributions do not and will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark, trade secret, or moral rights of any third party.</li>
                            <li>You are the creator and owner of or have the necessary licenses, rights, consents, releases, and permissions to use and to authorize us, the Site, and other users of the Site to use your Contributions in any manner contemplated by the Site and these Terms of Use.</li>
                            <li>You have the written consent, release, and/or permission of each and every identifiable individual person in your Contributions to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of your Contributions in any manner contemplated by the Site and these Terms of Use.</li>
                        </ul>
                        <h4>User Content: Your Ownership and Our License to Use</h4>
                        <p>
                            You represent and warrant that you are the owner or otherwise have the right to provide any information, reviews or photos (described in Interactive Areas below) or materials (including pre-existing materials) and any comments or content submitted, posted or transmitted
                            through the Sites (“User Content”). By submitting communications or content to any interactive part of our Sites, you agree that such submission is non-confidential for all purposes and that any inclusion of personally identifiable information, such as name, photograph
                            or other information in such posts may allow others to identify you.
                        </p>
                        <h4>Interactive Areas</h4>
                        <p>
                            We may provide interactive activities for the Sites’ communities such as chat rooms, article and blog comment posting areas, reader photo upload, reader ratings and reviews, bulletin boards (also known as message boards), SMS text messaging and mobile alerts (collectively, "Interactive Areas") for the enjoyment of our visitors.
                        </p>
                        <p>
                            Any submissions or postings by visitors to certain parts of the Sites, including, without limitation, Interactive Areas, will be public and posted in public areas on our Sites. The Sites, their parents, partners, affiliates, subsidiaries, members, directors, officers, employees and any contract or operational 
                            providers that conduct, operate and/or manage the Sites’ Interactive Areas will not be responsible for the action of any visitors or third parties with respect to any information, materials or content posted, uploaded or transmitted in these Interactive Areas.
                        </p>
                        <p>
                            You must be thirteen (13) years of age or older to participate in the Sites’ Interactive Areas. General members of the Sites’ online communities may have the opportunity to register for participation in the Interactive Areas when they first apply for membership and may be required to select a member name and password for the 
                            Interactive Areas. Interactive Areas not conducted, operated and/or managed by the Sites may require a different registration process.
                        </p>
                        <p>
                            Please consider the risks of revealing personal information (such as name, phone number or street address) about yourself or others in Interactive Areas, including when connecting to the Sites through a third party service. By participating in any of the aforementioned activities, all visitors and members agree to follow the
                            Sites' standards of conduct. Postings to public areas may or may not be reviewed by the Sites prior to appearing on the Sites. Nonetheless, the Sites reserve the right to change, delete or remove, in part or in full, any postings in Interactive Areas and to terminate or suspend access to such areas for conduct that we believe, 
                            in our sole discretion, interferes with other peoples' enjoyment of our Sites. The Sites will also cooperate with local, state and/or federal authorities to comply with applicable law.
                        </p>
                    </div>
                </div>
            </div>
        </section> 
        <section class="service-nd-mission tc-padding-top white-bg">
            <div class="container">
                <div class="main-heading-holder">
                    <div class="main-heading style-1">
                        <h2><span class="theme-color">DELIVERY POLICY</span></h2>
                    </div>
                </div>
                <div class="our-service tc-padding-bottom">
                    <div class="row">
         
                        <h4>Shipping Address</h4>
                        <p>
                  Your shipping address and pin code will be verified with the database of Skyevo before You proceed to pay for Your purchase. In the event Your order is not serviceable by our logistics service providers or the area is not covered, we will request You to provide us with an alternate shipping address. You can make purchases on the Website/App from anywhere in the world but at the same time You must ensure the payment and shipping address is within India.
                        </p>
                        <p>When You submit an alternative address for delivery, You are responsible for accepting and collecting the package from such alternative address. Confirmation from the logistics service provider of successful delivery to the alternative shipping address is deemed as acceptance of delivery by You and Skyevo will have no liability in this regard.</p>
                        <p>Delivery to Partner Store (subject to the availability of function and the facilities by seller)</p>
                        <p>Instead of delivering the order to Your shipping address, You can choose to have Your product delivered to a partner store so You can pick-up the package from the partner store at Your convenience. On Your collecting the package You will receive a notification by email or SMS at the email address or mobile number provided to Skyevo confirming delivery of the product. Click here to get a list of our partner stores. If You do not collect the product from the partner store within allowed time, the product will be returned to the seller and Your order will be cancelled. No refund due to non-deliverability will be applicable to orders placed with Cash on Delivery options.</p>
                        <h4>Multiple Product Orders</h4>
                        <p>
                    In case You order multiple products in one transaction, Skyevo would endeavour to ship all products together. However, this may not always be possible due to some product characteristics or logistics issues or the location of seller and You may receive the products separately and at different times. If You purchase multiple products in a single transaction, then all the products would be dispatched to a single shipping address given by You. If You wish to ship products to different addresses, then You should book the orders separately based on the shipping addresses.
                        </p>
                     
                   
                        <h4>Missing Items</h4>
                        <p>
                          In the event, the product package received by You is missing one or more products or accessories or does not include the freebie or the order is partly delivered, You should inform Skyevo through the Customer Care Team within 5 days of delivery date of the package. Missing products claims will not be accepted after 5 days from delivery date. 

                        </p>
                        <p>
                           In the event, the product package received by You is missing one or more products or accessories or does not include the freebie or the order is partly delivered, You should inform Skyevo through the Customer Care Team within 5 days of delivery date of the package. Missing products claims will not be accepted after 5 days from delivery date. 
                        </p>
                           <h4>Refusal of Delivery</h4>
                        <p>
                           Before accepting delivery of any product, kindly ensure that the product's packaging is not damaged or tampered. If You observe that the package is damaged or tampered, You are requested to refuse to accept delivery and inform Skyevo within 5 days of delivery date.

                        </p>
                        <p>You are requested to fill the delivery sheet / acknowledgement used by the logistics service providers and note down the condition of the delivered package. Damaged or tampered products claims will not be accepted beyond the returns policy.</p>
                        
                        <h4>Delivery Time</h4>
                        <p>
                            An estimated delivery time of each product will be displayed on the [‘product order page’]. On placing Your order, You will receive an email or SMS at the email address or mobile number provided to Skyevo containing a summary of the order and also the estimated delivery time to Your location. 
                        </p>
                        <p>Delivery timeframes are just estimates and are not guaranteed delivery timeframes and should not be relied upon as such. Deliveries to certain locations may take longer than expected due to accessibility of the location and serviceability by the logistics service provider.</p>
                        <h4>About Delayed Delivery</h4>
                        <p>Sometimes, delivery may take longer due to:</p>
                        <ul class="list_1"style="font-size:16px;">
                        <li>Bad weather.</li>
                            <li>Transportation delays.</li>
                            <li>Natural calamities.</li>
                            <li>Political disruptions.</li>
                            <li>Logistics service provider related challenges.</li>
                            <li>Product lost in transit.</li>
                            <li>Regional or national holidays which are considered as delivery holidays.</li>
                            <li>Other unforeseen circumstances or events beyond the control of Skyevo or logistics service provider.</li>
                        </ul>
                        <h4>User Content: Your Ownership and Our License to Use</h4>
                        <p>
                            You represent and warrant that you are the owner or otherwise have the right to provide any information, reviews or photos (described in Interactive Areas below) or materials (including pre-existing materials) and any comments or content submitted, posted or transmitted
                            through the Sites (“User Content”). By submitting communications or content to any interactive part of our Sites, you agree that such submission is non-confidential for all purposes and that any inclusion of personally identifiable information, such as name, photograph
                            or other information in such posts may allow others to identify you.
                        </p>
                
                        <p>
                            If the estimated delivery date has passed and You still have not received Your order, please contact us and we will take steps to track Your package. In such cases, we may also try to proactively contact You. Please check Your emails and SMS regularly for such updates.
                        </p>
                        <p>
                            Any submissions or postings by visitors to certain parts of the Sites, including, without limitation, Interactive Areas, will be public and posted in public areas on our Sites. The Sites, their parents, partners, affiliates, subsidiaries, members, directors, officers, employees and any contract or operational 
                            providers that conduct, operate and/or manage the Sites’ Interactive Areas will not be responsible for the action of any visitors or third parties with respect to any information, materials or content posted, uploaded or transmitted in these Interactive Areas.
                        </p>
                        <p>
                            Skyevo will not compensate for any mental agony or inconvenience or loss caused due to delay in delivery for any reason. You may be informed by email or SMS at the email address or mobile number provided to Skyevo if any product in the order is unavailable or is delayed or lost in transit.
                        </p>
                        <h4>Shipping Charges</h4>
                        <p>
                        You may be required to pay Shipping Charges in addition to the order value amount. The shipping charges, if any, will appear at the time of checkout. All delivery charges are inclusive of service tax unless stated otherwise. Shipping Charges may vary for different pin code because of the increase in shipping cost or seller’s is located in a different area. Delivery charges will vary according to pin codes as well as type of product.
                        </p>
                        <h4>Open delivery</h4>
                        <p>Skyevo reserves the right to provide Open delivery or not. Open delivery service which is provided by Skyevo with some Specifics logistics service providers. Open delivery depends upon our logistics service provider’s service dependencies. You can’t open parcel if logistics service provider doesn’t allow and in such event, You have a right to accept the parcel after paying the amount and thereafter You can use our hassle-free return policy.
Please refer to the Return and Refund Policies, if You wish to return the delivered product to Skyevo.
</p>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <?php
        include './include/footer.php';
    ?>
</div>
<script src="js/vendor/jquery.js"></script>        
<script src="js/vendor/bootstrap.min.js"></script>
<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script src="js/gmap3.min.js"></script>					
<script src="js/datepicker.js"></script>					
<script src="js/contact-form.js"></script>					
<script src="js/bigslide.js"></script>					
<script src="js/3d-book-showcase.js"></script>					
<script src="js/turn.js"></script>							
<script src="js/jquery-ui.js"></script>								
<script src="js/mcustom-scrollbar.js"></script>					
<script src="js/timeliner.js"></script>					
<script src="js/parallax.js"></script>			   	 
<script src="js/countdown.js"></script>	
<script src="js/countTo.js"></script>		
<script src="js/owl-carousel.js"></script>	
<script src="js/bxslider.js"></script>	
<script src="js/appear.js"></script>		 		
<script src="js/sticky.js"></script>			 		
<script src="js/prettyPhoto.js"></script>			
<script src="js/isotope.pkgd.js"></script>					 
<script src="js/wow-min.js"></script>			
<script src="js/classie.js"></script>					
<script src="js/main.js"></script>				
</body>
</html>